name: Publish

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
      - uses: totto2727-org/monorepo/.github/actions/setup-nix@050a0db1c73bfd8ddc0816c2c6414fd3d03fabf4
      - uses: totto2727-org/monorepo/.github/actions/publish-moonbit@050a0db1c73bfd8ddc0816c2c6414fd3d03fabf4
        with:
          token: ${{ secrets.MOONCAKES_TOKEN }}
