name: Publish

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: Confirm that this publishes totto2727/x.
        required: true
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  publish:
    if: inputs.confirm
    environment: mooncakes-production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: totto2727-org/monorepo/.github/actions/setup-nix@main
      - uses: totto2727-org/monorepo/.github/actions/publish-moonbit@main
        with:
          token: ${{ secrets.MOONCAKES_TOKEN }}
