name: Publish

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: totto2727-org/monorepo/.github/actions/setup-nix@main
      - uses: totto2727-org/monorepo/.github/actions/publish-moonbit@main
        with:
          token: ${{ secrets.MOONCAKES_TOKEN }}
